Allow username, password and key from env/secret
FNNDSC/docker-swift-onlyone pull request #2
Opened 2021-05-01 13:06 UTC by zrthxn

Closes: https://github.com/FNNDSC/ChRIS_store/issues/20

## Description
Added shell code to allow Swift username, password and key to be set via environment variables or docker secrets.

### Behavior of the variables being set
- If environment variables are given via the -e option, use these variables first.
- Else if `credentials.env` file exists, use file to set environment variables.
- If docker secret `swift-credentials` is set and the file exists, take precedence over environment variables.

2021-05-01 13:07 UTC, zrthxn commented
@jbernal0019 @jennydaman Related to the hardcoded secrets issue in Swift storage service.

2021-05-05 15:05 UTC, jennydaman requested changes

2021-05-05 15:05 UTC, jennydaman commented on files/startmain.sh
> +		sed -i -e "s/$line/export $line/g" /etc/swift/credentials.temp
Are you trying to prepend `export` to every line of the file?

```shll
sed -i -e 's/^/export /g' /etc/swift/credentials.temp
```

2021-05-05 15:05 UTC, jennydaman commented on files/startmain.sh
> +	cp /etc/swift/credentials.env /etc/swift/credentials.temp
I recommend using `mktemp`

2021-05-05 16:19 UTC, zrthxn commented on files/startmain.sh
> +		sed -i -e "s/$line/export $line/g" /etc/swift/credentials.temp
Yes but I think the way I did it, you'd be able to control which lines to add `export` to by checking `$line`, like for example to check whether or not the line has an acceptable variable name

2021-05-05 18:52 UTC, jbernal0019 commented
This looks like a great contribution @zrthxn! Could we instead of having three env variables just have these two:

1. SWIFT_USERNAME
2. SWIFT_KEY

For instance `SWIFT_USERNAME=chris:chris1234` and `SWIFT_KEY=testing`.  That way we won't need to change any of our current deployments and development files.

2021-05-05 19:09 UTC, zrthxn commented
@jbernal0019 Yes of course, that's what I had thought of initially. It needed some pattern matching so I didn't like that approach. But I'll try it out anyway.

2021-05-06 18:14 UTC, jennydaman requested changes

2021-05-06 18:14 UTC, jennydaman commented on files/startmain.sh
> +if [ -e /run/secret/swift-credentials ]; then
I would recommend allowing for the user to either:

- specify credentials via environment variables `SWIFT_USERNAME`
- specify credentials by giving a file path via environment variable `CREDENTIALS_FILE` (takes precedent)

The code would look something like this:

```bash
SWIFT_USERNAME="${SWIFT_USERNAME:-chris:chris1234}"
if [ -v CREDENTIALS_FILE ]; then
  source $CREDENTIALS_FILE
fi
export SWIFT_USERNAME
```

Also note: instead of using `sed` to export everything in the given `.env`, it's safer (and faster) to selectively export explicitly what we want: only `SWIFT_USERNAME` and `SWIFT_KEY`
... that is, if we need to be exporting these variables anyway. It seems like they're not being used by subprocesses and only as local variables, then written into `/etc/swift/dispersion.conf`?

Instead of using `sed` again on `/etc/swift/dispersion.conf` I think a heredoc would be easier (and faster)

```bash
cat > /etc/swift/dispersion.conf << EOF
[dispersion]
auth_url = http://127.0.0.1:8080/auth/v1.0
auth_user = $SWIFT_USERNAME
auth_key = $SWIFT_KEY
endpoint_type = internalURL
EOF
```

2021-05-06 20:59 UTC, zrthxn commented on files/startmain.sh
> +if [ -e /run/secret/swift-credentials ]; then
So instead of prepending "export" and then source-ing that file, like here
https://github.com/FNNDSC/docker-swift-onlyone/blob/39943ff5fadab12e61d978def835deb4032ff29b/files/startmain.sh#L80-L82

I can just extract the variable values from the file and put those into the local variables. Then continue using `sed` to modify the `/etc/swift/proxy-server.conf` and `/etc/swift/dispersion.conf` files, since that allows other values to remain unchanged from what the user set them to like the `auth_url`.

2021-05-06 21:57 UTC, jennydaman commented on files/startmain.sh
> +if [ -e /run/secret/swift-credentials ]; then
I recommend using a heredoc instead of `awk`/`sed`/`cut` because it's more legible and does not use child processes.

2021-05-06 22:04 UTC, zrthxn commented on files/startmain.sh
> +if [ -e /run/secret/swift-credentials ]; then
How would I go about keeping the rest of the file unchanged/as it was (modified or not), with a heredoc?

2021-05-06 22:10 UTC, jennydaman commented on files/startmain.sh
> +	SWIFT_USERNAME = awk '/SWIFT_USERNAME/' /etc/swift/credentials.env | cut -f2 -d=
A PCRE look-behind

```
grep -m 1 -Po '(?<=SWIFT_USERNAME).+'
```

2021-05-06 22:11 UTC, jennydaman commented on files/startmain.sh
> +if [ -e /run/secret/swift-credentials ]; then
Maybe distasteful, but put the entire config file as a heredoc inside the script.

2021-05-06 22:15 UTC, zrthxn commented on files/startmain.sh
> +if [ -e /run/secret/swift-credentials ]; then
Even though that'll make the conf files sort of ineffective?

2021-05-06 22:16 UTC, jennydaman commented on files/startmain.sh
> +if [ -e /run/secret/swift-credentials ]; then
What do you mean by ineffective?
Do you mean, `git rm` them?

2021-05-06 22:20 UTC, zrthxn commented on files/startmain.sh
> +if [ -e /run/secret/swift-credentials ]; then
No I mean if the heredoc is setting the content of the file, then whatever changes you make to the config before building the image won't work because the script will modify the file and remove them.

2021-05-06 22:23 UTC, jennydaman commented on files/startmain.sh
> +if [ -e /run/secret/swift-credentials ]; then
Do you think we should support having the image be customizable by adding your own files, or should we only support customization via the environment variables we've chosen to expose?

2021-05-06 22:29 UTC, zrthxn commented on files/startmain.sh
> +if [ -e /run/secret/swift-credentials ]; then
I think it should be customisable. This isn't an app that we're building, it's essentially just a config for setting up Swift. So I think it should allow maximum configuration of the actual application underneath, otherwise it sort of misses the point, doesn't it?

2021-05-06 22:45 UTC, jennydaman commented on files/startmain.sh
> +if [ -e /run/secret/swift-credentials ]; then
Earlier today we've discussed senarios where less customization is preferable.

This is a somewhat opinionated configuration of swift, intended for development purposes. Hence I think less (and/or easier) code and fewer decisions is advantageous.

2021-05-06 22:49 UTC, zrthxn commented on files/startmain.sh
> +if [ -e /run/secret/swift-credentials ]; then
Alright then I'll use the the suggested method.

2021-05-07 10:06 UTC, zrthxn commented on files/startmain.sh
> +	SWIFT_USERNAME = awk '/SWIFT_USERNAME/' /etc/swift/credentials.env | cut -f2 -d=
This regex is not working right. It doesn't get any results.

![Screenshot (66)](https://user-images.githubusercontent.com/35369637/117434077-da027680-af49-11eb-9794-6bd4fa03e4d5.png)

I found that this works

```bash
grep -m 1 -Po '(?<=SWIFT_USERNAME.)[A-Za-z0-9\:]*'
```

![Screenshot (69)](https://user-images.githubusercontent.com/35369637/117434186-fe5e5300-af49-11eb-9b73-d54abe57fe06.png)

2021-05-08 18:28 UTC, jennydaman requested changes

2021-05-08 18:28 UTC, jennydaman commented on files/startmain.sh
> +cat > /etc/swift/dispersion.conf << EOF
If we're using heredoc, `swift/credentials.env` and `swift/dispersion.conf` are not necessary and should be removed from this repo.

2021-05-08 18:28 UTC, jennydaman commented on files/startmain.sh
> +	SWIFT_USERNAME = grep -m 1 -Po '(?<=SWIFT_USERNAME.)[A-Za-z0-9\:]*' /etc/swift/credentials.env
Why not just `.+`? The `SWIFT_USERNAME` should be allowed to have non-alphanumeric characters like `-+=`

2021-05-08 18:28 UTC, jennydaman commented on files/startmain.sh
> +	SWIFT_KEY=`pwgen 12 1`
I think random password generation is feature creep (UNIX philosophy is to do one thing and one thing well, let `pwgen` be something used outside of `docker-swift-onlyone`)

Alternatively, keep the random password feature for the sake of developer's convenience. But I'd prefer to use standard tools so we can drop the `pwgen` dependency.


```bash
generate_password ()
{
  head /dev/urandom | tr -dc A-Za-z0-9 | head -c "${1:-60}"
}
```

2021-05-08 18:29 UTC, jennydaman commented on files/startmain.sh
> +	SWIFT_KEY=`pwgen 12 1`
Nevermind, developer's convenience would be a default password e.g. `chris:chris1234`

I'd suggest removing this feature and removing `pwgen`

2021-05-08 18:31 UTC, zrthxn commented on files/startmain.sh
> +	SWIFT_KEY=`pwgen 12 1`
I just kept it because it was already there.
https://github.com/FNNDSC/docker-swift-onlyone/blob/224ae1f938d6d6bc1316ffed04855632818c3ff0/files/startmain.sh#L62

2021-05-08 18:35 UTC, zrthxn commented on files/startmain.sh
> +cat > /etc/swift/dispersion.conf << EOF
Could remove `dispersion.conf` although maybe `credentials.env` would be helpful as a reference?

2021-05-08 18:36 UTC, zrthxn commented on files/startmain.sh
> +	SWIFT_USERNAME = grep -m 1 -Po '(?<=SWIFT_USERNAME.)[A-Za-z0-9\:]*' /etc/swift/credentials.env
For some reason `.+` seems [not to work](https://github.com/FNNDSC/docker-swift-onlyone/pull/2#discussion_r628088629)

2021-05-08 19:21 UTC, jennydaman commented on files/startmain.sh
> +	SWIFT_KEY=`pwgen 12 1`
Yeah I saw that, but I think it is a bad idea.

2021-05-12 18:33 UTC, jennydaman commented on files/startmain.sh
> +	SWIFT_USERNAME = awk '/SWIFT_USERNAME/' /etc/swift/credentials.env | cut -f2 -d=
What is the output of `grep --version`?

Have you tried using a container?

```bash
$ cat example.env | docker run --rm -i ubuntu:18.04 grep -m 1 -Po '(?<=SWIFT_USERNAME).+
=chris:chris1234
```

(my original example should be modified to include a `=` at the end of the look-ahead)

When you encounter a problem, I would only move onto a workaround (at the cost of a feature, in this case, allowing non-alphanumeric characters in a password) when you have figured out what the problem is and know for sure you can't fix it yourself. Otherwise I would've gone with your original solution (`awk ... | cut ...`).

Moreover, this behavior should be documented. If you want to restrict the keyspace, then you need to write in the README that `SWIFT_USERNAME` must be alphanumeric characters only. You must also describe how whitespace is not tolerated and the string should not be wrapped in quotation marks.

This is another advantage of

```bash
source swift/credentials.env
export SWIFT_USERNAME
export SWIFT_KEY
```

You could simply document that the format of `.env` (which is not a formally defined file format) obeys the rules of bash, which might be convenient because all the following are permitted:

```bash
SWIFT_USERNAME='$::'
SWIFT_USERNAME="$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c "${1:-60}")"
SWIFT_USERNAME="alice:bob"
SWIFT_USERNAME=alice:bob
SWIFT_USERNAME=$USER:chris1234
```

2021-05-13 08:21 UTC, zrthxn commented on files/startmain.sh
> +	SWIFT_USERNAME = awk '/SWIFT_USERNAME/' /etc/swift/credentials.env | cut -f2 -d=
@jennydaman 

I did try my best to understand what the problem was but with every combination I tried in the regex, I'd either just get a blank output or just a single character.

> What is the output of grep --version?

![Screenshot (70)](https://user-images.githubusercontent.com/35369637/118097547-761bfa00-b3f0-11eb-9ed9-e6bc670b4ebc.png)


> Have you tried using a container?

I have now, and it seems to work.
![Screenshot (71)](https://user-images.githubusercontent.com/35369637/118098563-ad3edb00-b3f1-11eb-95b0-3600fc973ca7.png)

So since exporting the credentials file gives us more flexibility, do you want to revert to that? Or do you want to continue using the grep method?

2021-05-13 16:33 UTC, jennydaman commented on files/startmain.sh
> +	SWIFT_USERNAME = awk '/SWIFT_USERNAME/' /etc/swift/credentials.env | cut -f2 -d=
My opinion is that `source ... && export SWIFT_USERNAME SWIFT_KEY` is more convenient (in this case, in high-security environments we would want to avoid using `source`).

If you'd like to continue troubleshooting your `grep` try using a different shell, 

```shell
sh -c 'grep -m 1 -Po "(?<=SWIFT_USERNAME).+" swift/credentials.env'
```

2021-05-13 17:20 UTC, zrthxn commented
@jennydaman Reverted to source-ing

2021-05-13 17:27 UTC, jennydaman commented
@zrthxn my previous suggestion was to export the variables after sourcing, and avoid using `sed`

```bash
source $CREDENTIALS
export SWIFT_USERNAME SWIFT_KEY
```

It would also be good to write a few unit tests and use Github Actions. lmk if you need help with Github Actions.

2021-05-13 17:30 UTC, zrthxn commented
Oh alright. I do know about Actions, although I'm not sure what the unit tests would test for? Should they check the variables that the script uses or check the supervisord things?

2021-05-13 17:35 UTC, jennydaman commented
Just to test that a minimal setup works.

Basically, just an upload and download.

```bash
swift -U chris:chris1234 -A http://localhost:8080/auth/v1.0  -K testing upload users LICENSE.txt --object-name apath/LICENSE.txt
swift -U chris:chris1234 -A http://localhost:8080/auth/v1.0  -K testing download users /tmp --prefix $FILE apath/LICENSE.txt
diff -q LICENSE.txt /tmp/LICENSE.txt
```

And then duplicate this test to make sure a custom password works as well, a docker secret works, ...

2021-05-18 13:40 UTC, zrthxn commented
@jennydaman 
Tests are passing now
https://github.com/zrthxn/docker-swift-onlyone/runs/2610924992

If these are okay then I'll just change `.github/workflows/docker-image.yml` to run only on Pull requests to `master`

2021-05-20 14:59 UTC, jennydaman requested changes

2021-05-20 14:59 UTC, jennydaman commented on .github/workflows/docker-deploy.yml
> +      run: echo DockerHub
We do not need this file.

2021-05-20 14:59 UTC, jennydaman commented on .github/workflows/docker-image.yml
> +        sudo apt-get install -y python3-pip
We do not need `sudo apt-get`. [`pip` is pre-installed](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md). For advanced Python config (which shouldn't be necessary) use [`actions/seup-python@v2`](https://github.com/actions/setup-python)

Here is an example for both how to use `pip` in vanilla Github Actions or `actions/setup-python@v2`
https://github.com/FNNDSC/chrisapp/blob/dcc6e4493b1592f2dff09e316847fe7e02e7dd42/.github/workflows/test.yml#L33-L34

2021-05-20 14:59 UTC, jennydaman commented on .github/workflows/docker-image.yml
> +    - name: Test OpenStack Swift [default]
Completely optional challenge, do you want to try parallelizing these tests using jobs?

2021-05-20 14:59 UTC, jennydaman commented on .github/workflows/docker-image.yml
> +        swift -A http://localhost:12345/auth/v1.0 -U chris:chris1234 -K testing download users README.md --output /tmp/README.md
Pedantic, I'd use `mktemp` here.

2021-05-20 14:59 UTC, jennydaman commented on files/startmain.sh
> +user_$(echo $SWIFT_USERNAME | sed 's/:/_/g') = $SWIFT_KEY .admin" >> /etc/swift/proxy-server.conf
This solution forbids the username and password from containing the `:` character, would you

1. explicitly document this in the `README.md`?
2. change the `sed` expression to not use the `g` (as in global) flag so that the restriction applies to only the username, i.e. (potentially*) permit `:` as a valid password character

```bash
echo hello:world:goodbye | sed 's/:/_/'
hello_world:goodbye
```


*footnote: I don't know how this would actually end up working in `proxy-server.conf`

2021-05-20 19:48 UTC, zrthxn commented on files/startmain.sh
> +user_$(echo $SWIFT_USERNAME | sed 's/:/_/g') = $SWIFT_KEY .admin" >> /etc/swift/proxy-server.conf
The colon character cannot be allowed in the variable because although it'd be replaced by an underscore in `proxy-server.conf`, it'd probably cause issues in `dispersion.conf`. I'll document this in the readme.

2021-05-20 20:07 UTC, zrthxn commented on .github/workflows/docker-image.yml
> +    - name: Test OpenStack Swift [default]
As far as I know (and have googled), I don't think that is possible in this particular case. I did try this before putting them into the same job, you can see that in the commit history.

Of course the three test steps can be run as parallel jobs, and they can use the `needs` keyword to wait for the build job to complete before starting. BUT since they need the docker image that was built by the previous job, they need to be on the same "runner", and at the moment there's no way to specify where a specific job (or step of a job) should run.

One solution could be to maybe upload the built docker image somewhere and then pull it into the test runners. But that'd just create more work than it's worth, with not enough speed improvements.

2021-05-22 13:31 UTC, zrthxn commented on .github/workflows/docker-image.yml
> +    - name: Test OpenStack Swift [default]
So I was able to make it work with artifacts!

2021-05-24 16:17 UTC, jennydaman requested changes

2021-05-24 16:17 UTC, jennydaman commented on .github/workflows/docker-image.yml
> +        cd
This `cd` (back to the home dir) is unnecessary.
How about simply `docker load < /tmp/artifacts/docker-image.tar`?

2021-05-24 16:17 UTC, jennydaman commented on .github/workflows/docker-image.yml
> +        sudo pip install python-swiftclient
Avoid `sudo` if unnecessary.
https://github.com/FNNDSC/docker-swift-onlyone/pull/2#discussion_r636179165

2021-05-24 16:17 UTC, jennydaman commented on .github/workflows/docker-image.yml
> +        docker run -d --name swift-onlyone -p 12345:8080 -v swift_storage:/srv -t fnndsc/docker-swift-onlyone:test
What is the volume for?

2021-05-24 16:17 UTC, jennydaman commented on .github/workflows/docker-image.yml
> +        swift -A http://localhost:12345/auth/v1.0 -U chris:chris1234 -K testing stat
I would put this in another step (for friendlier output).

2021-05-24 16:17 UTC, jennydaman commented on .github/workflows/docker-image.yml
> +        sudo pip install python-swiftclient
Same advice from above applies here.

2021-05-24 17:09 UTC, zrthxn commented on .github/workflows/docker-image.yml
> +        sudo pip install python-swiftclient
I did try it without sudo, it seems to give an error.

2021-05-24 17:10 UTC, zrthxn commented on .github/workflows/docker-image.yml
> +        docker run -d --name swift-onlyone -p 12345:8080 -v swift_storage:/srv -t fnndsc/docker-swift-onlyone:test
Oh that was just the run command that was in the readme which got copied. Sorry about that.

2021-05-24 17:11 UTC, zrthxn commented on .github/workflows/docker-image.yml
> +        swift -A http://localhost:12345/auth/v1.0 -U chris:chris1234 -K testing stat
Sure. Will do.

2021-06-07 18:18 UTC, zrthxn commented on .github/workflows/docker-image.yml
> +        sudo pip install python-swiftclient
I've removed sudo now, it works fine. sorry about the trouble.

2021-06-14 07:51 UTC, jennydaman approved these changes

2021-06-14 07:51 UTC, jennydaman commented on .github/workflows/docker-image.yml
> +        sudo pip install python-swiftclient
Sorry for missing this comment. 

Would you be specific about what error it gave you?

2021-06-14 08:27 UTC, zrthxn commented
@jennydaman 
That error was when I was using apt to install python-swiftclient
https://github.com/zrthxn/docker-swift-onlyone/blob/e8dcf896ecc68beb421425ec69098912a5a446e1/.github/workflows/docker-image.yml#L16-L18

https://github.com/zrthxn/docker-swift-onlyone/runs/2609372453?check_suite_focus=true#step:3:1124
```
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
Error: Process completed with exit code 100.
```

2021-06-14 08:38 UTC, jennydaman commented
@zrthxn If `SWIFT_USERNAME` is defined in the environment, then `SWIFT_KEY` must also be defined by the environment.
i.e., it is unsupported to have a custom `SWIFT_USERNAME` and the default value for `SWIFT_KEY`.
Would you support this behavior, or document it in the README?

2021-06-14 08:46 UTC, zrthxn commented
Since both of them are important to the security of the storage, they should both be defined by the user any time that this container is started. So I'll document that the user must provide both of them. 
If they don't and they try to use just their custom username+password to access Swift, they'll get access denied which will hopefully tell them that something was wrong with their config.

2021-06-15 21:12 UTC, merged